### ISSUE TITLE
Erro na resposta de verificação do token

### ISSUE THREAD

**Issue by lucasca73** [fga-eps-mds/2018.2-FGAPP-login#12]
**Describe the bug**
Quando se entra com o token correto para ser verificado

<img src="https://user-images.githubusercontent.com/4529055/46771773-7e0cde00-cccb-11e8-82f3-8ea897af0ee0.png" width=200/>
<img src="https://user-images.githubusercontent.com/4529055/46771833-bb716b80-cccb-11e8-9159-76f73ad6b69b.png" width=200/>

Quando o token está errado aparece:
<img src="https://user-images.githubusercontent.com/4529055/46771873-d2b05900-cccb-11e8-93df-3847dbf1c1d8.png" width=200/>

**To Reproduce**
1. Subir serviço de login
2. cadastrar uma conta
3. colocar o token no body do post e mandar para http://localhost:8000/api/token-verify/

**Expected behavior**
repostas coerentes e sem erro 400

na resposta correta deve-se retornar por exemplo
```js
{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IiIsImV4cCI6MTUzOTIxMDMxMiwiZW1haWwiOiIiLCJvcmlnX2lhdCI6MTUzOTIxMDAxMn0.3l0HvjhgeH-IKknjRgiWmi4-ymt8aTOudigs-jFStBg"
}
```

**Comment by gustavolima00** [comment]
Ao testar na branch dev não consegui esse erro, testei de várias formas diferentes

### Não enviando nada:
![image](https://user-images.githubusercontent.com/32046134/46775367-4b6be100-ccdd-11e8-8f8b-83013090d485.png)

### Mandando o token em branco:
![image](https://user-images.githubusercontent.com/32046134/46775384-5cb4ed80-ccdd-11e8-9881-dd0ac992082c.png)

### Mandando um token errado:
![image](https://user-images.githubusercontent.com/32046134/46775394-6dfdfa00-ccdd-11e8-81d8-808e5aa02cd9.png)

### Mandando o token certo:
![image](https://user-images.githubusercontent.com/32046134/46775404-7c4c1600-ccdd-11e8-8a40-583fd36750eb.png)

**Comment by lucasca73** [comment]
Magias do Software
