### ISSUE TITLE
Confirmacao de email mal formatado

### ISSUE THREAD

**Issue by andrelucax** [fga-eps-mds/2018.2-FGAPP-login#29]
**Describe the bug**
Email de confirmacao de registro esta mal formatado.

**To Reproduce**
1. Cadastre um usuario com email valido
2. Veja caixa de email

**Expected behavior**
Se espera ou nao receber email ou que ele venha com formacao e links corretos.

**Screenshots**
![bug](https://user-images.githubusercontent.com/42394759/47953393-cf6f5c80-df5b-11e8-8df7-e33e49335dc3.jpg)

**Desktop (please complete the following information):**
 - OS: Ubunto 16.04

**Smartphone (please complete the following information):**
 - Device: Samsung J7

**Comment by andrelucax** [comment]
@lucasca73 Fiquei impossibilitado de testar a funcionalidade 100% devido alteracoes feitas nos seus ultimos commits. Agora o email esta aparecendo no terminal, porem nao contem o titulo, nao sendo possivel verificar como ele se encontra.

EDIT:
tentei rodar com o comando de producao e o email continua no terminal (era pra enviar normalmente nesse caso)

**Comment by lucasca73** [comment]
@andrelucax lancei um pull request pra auxiliar nesse problema. 
Execute o ```make production```, agora a configuração deve funcionar com esses últimos ajustes.
o .env deverá ser semelhante a isso
```
LOGIN_DOMAIN=192.168.1.3:8000
CDN_CLOUD_NAME=abc
CDN_API_KEY=123
CDN_API_SECRET=123
SECURITY_EMAIL_PASSWORD=123
```

**Comment by andrelucax** [comment]
Realizada no PR https://github.com/fga-eps-mds/2018.2-FGAPP-login/pull/32
